apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smoke-tests
  namespace: smoke-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: <path:secret/data/gcp/project/gke-cluster#tenant_cloudbuild>@cloudbuild.gserviceaccount.com
