apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-tests
  namespace: smoke-tests
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: smoke-tests
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smoke-tests
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - smoke-tests
              topologyKey: "kubernetes.io/hostname"
      containers:
        - command: ["/bin/bash", "-c", "sleep infinity"]
          image: <path:secret/data/gcp/project/gke-cluster#artifact_registry>/toolbox:latest
          imagePullPolicy: Always
          name: smoke-tests
          resources:
            requests:
              cpu: 125m
              #ephemeral-storage: 10Mi
              memory: 128Mi
            limits:
              cpu: 500m
              #ephemeral-storage: 10Mi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
