steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" -H "Metadata-Flavor: Google"
        gcloud config set core/project ${_PROJECT}
        gcloud container clusters get-credentials gke-autopilot --region us-central1 --project=${_PROJECT}
        kubectl get pods -n smoke-tests
